name: Create Tag

on:
    workflow_dispatch:
        inputs:
            tag:
                description: 'Version number (should start with "v", e.g. v1.0.0)'
                required: true
                type: string

permissions:
    contents: write # Required for creating tags

jobs:
    create_tag:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create and Push Tag
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git tag --annotate ${{ github.event.inputs.tag }} -m "Release ${{ github.event.inputs.tag }}"
                  git push origin ${{ github.event.inputs.tag }}

            - name: Verify Tag Creation
              run: git tag --list | grep ${{ github.event.inputs.tag }}
